import "./globals.css";
export const metadata={title:"Gigetto Ultra • Gemini Flash",description:"Infinite-ish quiz & minigames generated by Gemini Flash."};
export default function RootLayout({children}){return(<html lang="it"><body>{children}</body></html>)}
